name: 'Manual Build and Release'
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  name: Build Resource Pack
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
            ref: '${{ needs.version.outputs.tag }}'
      - name: Create Resource Pack File
        run: (cd VulkanMod\ Translations && zip -r "../VulkanMod_Translations.zip" *)
      - name: Generate Checksum
        run: >-
          sha1sum "VulkanMod_Translations.zip" | cut -d " " -f 1 >
          "VulkanMod_Translations.zip.sha1"
      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Resource Pack
          path: VulkanMod_Translations.zip*
      - name: Release on GitHub
        id: release-step
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: '${{ needs.version.outputs.tag }}'
          generate_release_notes: true
          files: VulkanMod_Translations.zip*
